### ISSUE TITLE
Where to put newrelic.jar?

### ISSUE THREAD

**Issue by Tropicalista** [mso-net/lucee-newrelic#1]
Hi I'm trying to use this component to connect to new relic. However I always get this error:

```
cannot load class through its string name, because no definition for the 
class with the specified name [com.newrelic.api.agent.NewRelic] could be found
```

I'm on lucee 4.5.1.024.
I have extracted the newrelic.jar in lib/newrelic and added javaagent to setenv. Is this correct? could you add a wiki or share a small guidance on how to get newrelic working? 

Thanks.

**Comment by andrew-dixon** [comment]
I just followed the install instructions from New Relic themselves here:

`https://docs.newrelic.com/docs/agents/java-agent/frameworks/tomcat-installation-java`

Adding the Java agent to the `JAVA_OPTS` in the `setenv.sh` file in the Tomcat `bin` directory.

Remember you have to restart Tomcat after adding this to that file for it to take affect.

**Comment by Tropicalista** [comment]
Yes, I've solved adding Java agent to Java_opts. Thanks
